# Generated by Django 5.2.17 on 2026-09-15 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalprofile',
            name='qr_code_uuid',
        ),
        migrations.RemoveField(
            model_name='clinicalprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clinicalprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clinicalprofile',
            name='medicines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalprofile',
            name='blood_type',
            field=models.CharField(default='O+', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicalprofile',
            name='emergency_phone',
            field=models.CharField(default='(47) 9999-9999', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
