# Generated by Django 5.2.17 on 2026-09-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_clinicalprofile_qr_code_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
