name: CI do Sistema Clínico

on:
  push:
    branches: [ "main" ]

jobs:
  testar-codigo:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: clinicdb
          POSTGRES_USER: tpassos
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências e rodar testes
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: localhost
      run: |
        pip install "psycopg[binary]" django qrcode pillow
        cd clinicDataViewer
        python manage.py test

  deploy:
      needs: testar-codigo
      runs-on: ubuntu-latest

      steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Executar deploy automatizado no EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/repos/clinic-data-viewer
            chmod +x deploy.sh
            ./deploy.sh
